spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop # DB?? url
    username: sa
    password:
    driver-class-name: org.h2.Driver #?????? ???? ??? ??? ?? ?? ??

  jpa:
    hibernate:
      # ???? ?? ??? ?? ??
      # ?????? ?? ??? ???? drop ??, ?? ??
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #`System.out` ? ?????? ?? SQL? ??
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug # logger? ?? ?????? ?? SQL? ??
    org.hibernate.orm.jdbc.bind: trace # ?? ???? ?? ??? (????? 3.x)





